/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryEquipmentIdRouteImport } from './routes/_app.inventory.$equipmentId'
import { Route as AppInventoryNewRouteImport } from './routes/_app.inventory.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryEquipmentIdRoute = AppInventoryEquipmentIdRouteImport.update({
  id: '/inventory/$equipmentId',
  path: '/inventory/$equipmentId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryNewRoute = AppInventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory/$equipmentId': typeof AppInventoryEquipmentIdRoute
  '/inventory/new': typeof AppInventoryNewRoute
  '/inventory/': typeof AppInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory/$equipmentId': typeof AppInventoryEquipmentIdRoute
  '/inventory/new': typeof AppInventoryNewRoute
  '/inventory': typeof AppInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory/$equipmentId': typeof AppInventoryEquipmentIdRoute
  '/_app/inventory/new': typeof AppInventoryNewRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inventory/$equipmentId'
    | '/inventory/new'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inventory/$equipmentId'
    | '/inventory/new'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/inventory/$equipmentId'
    | '/_app/inventory/new'
    | '/_app/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$equipmentId': {
      id: '/_app/inventory/$equipmentId'
      path: '/inventory/$equipmentId'
      fullPath: '/inventory/$equipmentId'
      preLoaderRoute: typeof AppInventoryEquipmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/new': {
      id: '/_app/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AppInventoryNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryEquipmentIdRoute: typeof AppInventoryEquipmentIdRoute
  AppInventoryNewRoute: typeof AppInventoryNewRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryEquipmentIdRoute: AppInventoryEquipmentIdRoute,
  AppInventoryNewRoute: AppInventoryNewRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
